name: Build LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex 
        uses: dante-ev/latex-action@latest
        with:
          working_directory: paper
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: paper/main.pdf
