name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main
      - name: Compile LaTeX document
        uses: BorisAndrews/Transfer_Thesis@main
        with:
          root_file: paper/main.tex
          compiler: pdflatex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
