name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Compile main.tex (pdflatex)
        uses: xu-cheng/latex-action@master
        with:
          root_file: paper/main.tex
      - name: Upload PDF
        uses: actions/upload-artifact@main
        with:
          name: PDF
          path: main.pdf
